#!/usr/bin/env bash

set -euf -o pipefail

DIRECTORY_THIS_SCRIPT=$(dirname "$(readlink -f "$0")")

. ${DIRECTORY_THIS_SCRIPT}/_dusage/venv/bin/activate

export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8

python3 ${DIRECTORY_THIS_SCRIPT}/_dusage/dusage $*
